// lib/quizData.ts
// Add more subjects and questions here, or swap with AI generation later

export interface Question {
  id: number;
  question: string;
  options: string[];
  answer: number; // index of correct option
  explanation?: string;
}

export interface Quiz {
  subject: string;
  slug: string;
  description: string;
  questions: Question[];
}

export const quizzes: Quiz[] = [
  {
    subject: "Programming in C",
    slug: "c-programming",
    description: "Test your knowledge of C fundamentals: from data types and pointers to file I/O and dynamic memory.",
    questions: [
      {
        id: 1,
        question: "Who created the C programming language?",
        options: ["Bjarne Stroustrup", "Dennis Ritchie", "Linus Torvalds", "Brian Kernighan"],
        answer: 1,
        explanation: "C was created by Dennis Ritchie at Bell Labs in the early 1970s.",
      },
      {
        id: 2,
        question: "Which flowchart symbol is used to represent a decision?",
        options: ["Rectangle", "Oval", "Parallelogram", "Diamond"],
        answer: 3,
        explanation: "A diamond shape represents a decision (conditional branch) in a flowchart.",
      },
      {
        id: 3,
        question: "What is the size of a `float` on a typical 32-bit system in C?",
        options: ["1 byte", "2 bytes", "4 bytes", "8 bytes"],
        answer: 2,
        explanation: "`float` is a 4-byte single-precision type; `double` is 8 bytes.",
      },
      {
        id: 4,
        question: "Which storage class retains a local variable's value between function calls?",
        options: ["auto", "extern", "register", "static"],
        answer: 3,
        explanation: "`static` local variables are initialized once and retain their value across calls.",
      },
      {
        id: 5,
        question: "What does `scanf(\"%d\", x)` have wrong compared to correct usage?",
        options: [
          "Wrong format specifier for int",
          "Missing & before x",
          "scanf cannot read integers",
          "Missing semicolon",
        ],
        answer: 1,
        explanation: "`scanf` needs the address of the variable: `scanf(\"%d\", &x)`. Without `&`, behavior is undefined.",
      },
      {
        id: 6,
        question: "In C, arrays are passed to functions as:",
        options: [
          "A full copy of the array",
          "A pointer to the first element",
          "A reference using the & operator",
          "A struct wrapper",
        ],
        answer: 1,
        explanation: "Array names decay to a pointer to their first element when passed to a function.",
      },
      {
        id: 7,
        question: "Which operator is used to access a structure member through a pointer?",
        options: [".", "->", "*", "&"],
        answer: 1,
        explanation: "The `->` operator dereferences a struct pointer and accesses a member: `ptr->field`.",
      },
      {
        id: 8,
        question: "What is the size of a `union` in C?",
        options: [
          "Sum of sizes of all members",
          "Size of the smallest member",
          "Size of the largest member",
          "Fixed 8 bytes",
        ],
        answer: 2,
        explanation: "All union members share the same memory, so the union is sized to fit its largest member.",
      },
      {
        id: 9,
        question: "Which dynamic memory function allocates memory AND zero-initializes it?",
        options: ["malloc", "realloc", "calloc", "alloc"],
        answer: 2,
        explanation: "`calloc(n, size)` allocates n elements of the given size and sets all bytes to zero.",
      },
      {
        id: 10,
        question: "What is the correct way to define a macro that squares a number safely?",
        options: [
          "#define SQR(x) x*x",
          "#define SQR(x) (x*x)",
          "#define SQR(x) ((x)*(x))",
          "#define SQR(x) {x*x}",
        ],
        answer: 2,
        explanation: "Parentheses around each argument and the whole expression prevent operator precedence bugs when the macro is used in complex expressions.",
      },
      {
        id: 11,
        question: "What type does `sizeof(char)` return in C?",
        options: ["int", "size_t", "char", "long"],
        answer: 1,
        explanation: "The `sizeof` operator returns `size_t`, an unsigned integer type used for sizes.",
      },
      {
        id: 12,
        question: "Which keyword tells the compiler that a variable is defined in another file?",
        options: ["auto", "register", "static", "extern"],
        answer: 3,
        explanation: "`extern` declares a variable defined in another translation unit.",
      },
      {
        id: 13,
        question: "Why is `fgets` preferred over `gets`?",
        options: ["gets is slower", "gets can overflow buffer", "fgets requires no arguments", "gets returns int"],
        answer: 1,
        explanation: "`gets` does not perform bounds checking and can overflow the buffer.",
      },
      {
        id: 14,
        question: "Which statement terminates the nearest enclosing loop or switch?",
        options: ["continue", "break", "return", "goto"],
        answer: 1,
        explanation: "`break` exits the nearest loop or switch statement.",
      },
      {
        id: 15,
        question: "What does `malloc(10 * sizeof(int))` return if memory allocation fails?",
        options: ["A null pointer", "A zeroed block", "An integer 0", "A dangling pointer"],
        answer: 0,
        explanation: "When allocation fails, `malloc` returns `NULL`.",
      },
      {
        id: 16,
        question: "How do you declare a pointer to an integer in C?",
        options: ["int *ptr;", "ptr int;", "int ptr*;", "int& ptr;"],
        answer: 0,
        explanation: "Pointer declaration uses `*` immediately before the pointer variable name.",
      },
      {
        id: 17,
        question: "If `enum { RED, GREEN, BLUE }` is declared, what is the value of `GREEN`?",
        options: ["0", "1", "2", "3"],
        answer: 1,
        explanation: "Enum values start at 0 unless specified otherwise.",
      },
      {
        id: 18,
        question: "Which function moves the file position indicator in a file stream?",
        options: ["fread", "fwrite", "fseek", "fprintf"],
        answer: 2,
        explanation: "`fseek` moves the file pointer to a new location.",
      },
      {
        id: 19,
        question: "What is the purpose of the `typedef` keyword?",
        options: ["Declare constants", "Rename types", "Allocate memory", "Create macros"],
        answer: 1,
        explanation: "`typedef` defines an alias for an existing type.",
      },
      {
        id: 20,
        question: "What does `*(&x)` evaluate to for a variable `x`?",
        options: ["The address of x", "The value of x", "Undefined", "A pointer to x"],
        answer: 1,
        explanation: "`&x` yields x's address, and `*` dereferences it back to x's value.",
      },
      {
        id: 21,
        question: "Which loop in C always executes its body at least once?",
        options: ["for", "while", "do...while", "switch"],
        answer: 2,
        explanation: "A `do...while` loop evaluates its condition after executing the body.",
      },
      {
        id: 22,
        question: "Which header file defines `malloc` and `free`?",
        options: ["stdio.h", "stdlib.h", "string.h", "math.h"],
        answer: 1,
        explanation: "Dynamic memory functions are declared in `stdlib.h`.",
      },
    ],
  },
  {
    subject: "Engineering Mathematics I",
    slug: "em1",
    description: "Review limits, differential calculus, and linear algebra fundamentals for first-semester engineering mathematics.",
    questions: [
      {
        id: 1,
        question: "What is the derivative of `sin(x)`?",
        options: ["cos(x)", "-cos(x)", "sin(x)", "-sin(x)"],
        answer: 0,
        explanation: "The derivative of `sin(x)` is `cos(x)`.",
      },
      {
        id: 2,
        question: "Which matrix operation is valid only for square matrices?",
        options: ["Addition", "Multiplication", "Determinant", "Scalar multiplication"],
        answer: 2,
        explanation: "Only square matrices have a determinant defined.",
      },
      {
        id: 3,
        question: "What is the limit of `(1 + 1/n)^n` as n approaches infinity?",
        options: ["0", "1", "e", "Infinity"],
        answer: 2,
        explanation: "The expression converges to Euler's number, `e`.",
      },
      {
        id: 4,
        question: "Which of these is a linear differential equation?",
        options: [
          "y' + 3y = 6",
          "y'² + y = 0",
          "y'' + y² = 5",
          "sin(y') + y = 0",
        ],
        answer: 0,
        explanation: "A linear differential equation has the unknown function and its derivatives to the first power only.",
      },
      {
        id: 5,
        question: "If a matrix has linearly dependent rows, what is true about its determinant?",
        options: ["It is positive", "It is negative", "It is zero", "It is undefined"],
        answer: 2,
        explanation: "A matrix with dependent rows has determinant zero.",
      },
      {
        id: 6,
        question: "What does the rank of a matrix represent?",
        options: [
          "The number of rows",
          "The number of independent rows or columns",
          "The determinant value",
          "The trace value",
        ],
        answer: 1,
        explanation: "Rank is the dimension of the row space or column space: the number of independent rows/columns.",
      },
      {
        id: 7,
        question: "Which of these is an example of a homogeneous linear equation?",
        options: ["2x + 3 = 0", "x² - 4 = 0", "3x + 5y = 0", "sin(x) = 1"],
        answer: 2,
        explanation: "A homogeneous linear equation has zero on the right-hand side.",
      },
      {
        id: 8,
        question: "The derivative of `e^{2x}` is:",
        options: ["2e^{x}", "e^{2x}", "2e^{2x}", "e^{x}"],
        answer: 2,
        explanation: "By chain rule, the derivative of `e^{2x}` is `2e^{2x}`.",
      },
      {
        id: 9,
        question: "Which integration rule is used for the integral of a product of functions?",
        options: ["Substitution", "Integration by parts", "Partial fractions", "Trigonometric substitution"],
        answer: 1,
        explanation: "Integration by parts applies to products of functions.",
      },
      {
        id: 10,
        question: "What is the solution of the linear system with coefficient matrix identity and vector b?",
        options: ["No solution", "b", "0", "Depends on the inverse"],
        answer: 1,
        explanation: "If Ax = b and A is the identity matrix, x = b.",
      },
      {
        id: 11,
        question: "What is the derivative of `ln(x)`?",
        options: ["1/x", "ln(x)", "x ln(x)", "-1/x"],
        answer: 0,
        explanation: "The derivative of `ln(x)` is `1/x` for x > 0.",
      },
      {
        id: 12,
        question: "What is the integral of `1/x dx` for x > 0?",
        options: ["x", "ln(x) + C", "1/x + C", "e^x + C"],
        answer: 1,
        explanation: "The antiderivative of `1/x` is `ln|x| + C`, which becomes `ln(x)+C` for x>0.",
      },
      {
        id: 13,
        question: "What is the slope of the tangent to y = x^2 at x = 3?",
        options: ["3", "6", "9", "12"],
        answer: 1,
        explanation: "The derivative of x^2 is 2x, so at x=3 the slope is 6.",
      },
      {
        id: 14,
        question: "For a 2x2 matrix [[a,b],[c,d]], when does the inverse exist?",
        options: ["Always", "When a ≠ 0", "When ad - bc ≠ 0", "When a + d ≠ 0"],
        answer: 2,
        explanation: "The inverse exists only when the determinant ad - bc is nonzero.",
      },
      {
        id: 15,
        question: "What is the area under y = x from 0 to 2?",
        options: ["1", "2", "3", "4"],
        answer: 1,
        explanation: "The integral of x from 0 to 2 is x^2/2 evaluated from 0 to 2, giving 2.",
      },
      {
        id: 16,
        question: "What is the determinant of [[1,2],[3,4]]?",
        options: ["-2", "2", "-5", "5"],
        answer: 0,
        explanation: "The determinant is 1*4 - 2*3 = -2.",
      },
      {
        id: 17,
        question: "What does row echelon form help solve?",
        options: ["Integrals", "Derivatives", "Linear systems", "Differential equations"],
        answer: 2,
        explanation: "Row echelon form is used to solve systems of linear equations.",
      },
      {
        id: 18,
        question: "A basis of a vector space must be:",
        options: ["Linearly independent only", "Span the space only", "Linearly independent and span the space", "Have exactly two vectors"],
        answer: 2,
        explanation: "A basis both spans the space and consists of linearly independent vectors.",
      },
      {
        id: 19,
        question: "What is the partial derivative of f(x,y) = x^2 y with respect to x?",
        options: ["2xy", "x^2", "y^2", "2x + y"],
        answer: 0,
        explanation: "Differentiating with respect to x treats y as constant, giving 2xy.",
      },
      {
        id: 20,
        question: "What is the second derivative of x^3?",
        options: ["3x^2", "6x", "x^3", "9x"],
        answer: 1,
        explanation: "The first derivative is 3x^2, so the second derivative is 6x.",
      },
      {
        id: 21,
        question: "Which series converges when |x| < 1?",
        options: ["Harmonic series", "Geometric series", "P-series with p=1", "Alternating series"],
        answer: 1,
        explanation: "A geometric series converges for |x| < 1.",
      },
      {
        id: 22,
        question: "What is the value of sin(π/6)?",
        options: ["0", "1/2", "1", "√2/2"],
        answer: 1,
        explanation: "sin(π/6) equals 1/2.",
      },
    ],
  },
  {
    subject: "Engineering Physics",
    slug: "ep",
    description: "Check your understanding of electric fields, magnetism, waves, and modern physics concepts from first-semester engineering physics.",
    questions: [
      {
        id: 1,
        question: "Which quantity is conserved in an elastic collision?",
        options: ["Momentum only", "Kinetic energy only", "Momentum and kinetic energy", "Neither"],
        answer: 2,
        explanation: "Elastic collisions conserve both momentum and kinetic energy.",
      },
      {
        id: 2,
        question: "What is the direction of the magnetic field around a straight current-carrying wire?",
        options: ["Radial", "Circular around the wire", "Parallel to current", "Random"],
        answer: 1,
        explanation: "The magnetic field lines form circles around the wire.",
      },
      {
        id: 3,
        question: "Which law relates magnetic flux to induced emf?",
        options: ["Ohm's Law", "Faraday's Law", "Coulomb's Law", "Newton's Second Law"],
        answer: 1,
        explanation: "Faraday's Law states that a changing magnetic flux induces an emf.",
      },
      {
        id: 4,
        question: "What is the SI unit of electric field strength?",
        options: ["Volt", "Newton per coulomb", "Tesla", "Coulomb"],
        answer: 1,
        explanation: "Electric field strength is measured in newtons per coulomb.",
      },
      {
        id: 5,
        question: "If the frequency of a wave doubles, its wavelength: ",
        options: ["Doubles", "Halves", "Remains unchanged", "Quadruples"],
        answer: 1,
        explanation: "For constant wave speed, wavelength is inversely proportional to frequency.",
      },
      {
        id: 6,
        question: "Which phenomenon demonstrates the particle nature of light?",
        options: ["Interference", "Diffraction", "Photoelectric effect", "Refraction"],
        answer: 2,
        explanation: "The photoelectric effect supports the particle nature of light.",
      },
      {
        id: 7,
        question: "What is the magnetic permeability of free space used to describe?",
        options: ["Electric field in vacuum", "Magnetic field in vacuum", "Resistance of a material", "Capacitance of a parallel-plate capacitor"],
        answer: 1,
        explanation: "Magnetic permeability describes how the magnetic field behaves in free space.",
      },
      {
        id: 8,
        question: "Which branch of physics studies motion without considering forces?",
        options: ["Dynamics", "Kinematics", "Optics", "Thermodynamics"],
        answer: 1,
        explanation: "Kinematics focuses on motion itself, not the forces causing it.",
      },
      {
        id: 9,
        question: "What is the unit of magnetic flux?",
        options: ["Tesla", "Weber", "Volt", "Henry"],
        answer: 1,
        explanation: "Magnetic flux is measured in webers.",
      },
      {
        id: 10,
        question: "Which is the term for lowest energy state of an atom?",
        options: ["Excited state", "Ground state", "Ionized state", "Metastable state"],
        answer: 1,
        explanation: "The ground state is the lowest energy state of an atom.",
      },
      {
        id: 11,
        question: "Coulomb's law says the force between two charges varies inversely with the square of: ",
        options: ["Their sum", "Their difference", "The distance between them", "The angle between them"],
        answer: 2,
        explanation: "Coulomb's law states force is inversely proportional to the square of the separation distance.",
      },
      {
        id: 12,
        question: "Gauss's law relates electric flux through a closed surface to:",
        options: ["Electric field strength", "Magnetic field strength", "Net charge enclosed", "Potential difference"],
        answer: 2,
        explanation: "Gauss's law connects flux through a closed surface with the enclosed charge.",
      },
      {
        id: 13,
        question: "In electrostatic equilibrium, the electric field inside a conductor is:",
        options: ["Maximum", "Minimum", "Zero", "Undefined"],
        answer: 2,
        explanation: "The electric field inside a conductor in equilibrium is zero.",
      },
      {
        id: 14,
        question: "Magnetic field lines are always:",
        options: ["Open-ended", "Circular around charges", "Closed loops", "Straight lines"],
        answer: 2,
        explanation: "Magnetic field lines form closed loops because magnetic monopoles do not exist.",
      },
      {
        id: 15,
        question: "The term describing the rate of change of magnetic flux is: ",
        options: ["Magnetic flux", "Induced emf", "Electric potential", "Capacitance"],
        answer: 1,
        explanation: "A changing magnetic flux induces an emf.",
      },
      {
        id: 16,
        question: "Maxwell added which term to Ampere's law to account for changing electric fields?",
        options: ["Displacement current", "Magnetic flux", "Electric charge", "Capacitance"],
        answer: 0,
        explanation: "Maxwell's displacement current term ensures continuity in Ampere's law.",
      },
      {
        id: 17,
        question: "Electromagnetic waves travel in vacuum at the speed of: ",
        options: ["Sound speed", "Speed of light", "Earth's rotation speed", "Zero"],
        answer: 1,
        explanation: "EM waves propagate at the speed of light in vacuum.",
      },
      {
        id: 18,
        question: "A material cooled below its critical temperature may become: ",
        options: ["Ferromagnetic", "Superconducting", "Insulating", "Transparent"],
        answer: 1,
        explanation: "Superconductors exhibit zero resistance below a critical temperature.",
      },
      {
        id: 19,
        question: "A solenoid carrying current creates a magnetic field similar to: ",
        options: ["A point charge", "A bar magnet", "A capacitor", "A resistor"],
        answer: 1,
        explanation: "A current-carrying solenoid produces a field like a bar magnet.",
      },
      {
        id: 20,
        question: "Which phenomenon demonstrates the wave nature of light?",
        options: ["Photoelectric effect", "Interference", "Photoemission", "Particle reflection"],
        answer: 1,
        explanation: "Interference is a wave phenomenon, showing light behaves as a wave.",
      },
      {
        id: 21,
        question: "A charged capacitor in steady DC conditions acts as a: ",
        options: ["Conductor", "Insulator", "Block to DC", "Current source"],
        answer: 2,
        explanation: "A fully charged capacitor blocks steady DC current.",
      },
      {
        id: 22,
        question: "The SI unit of capacitance is: ",
        options: ["Tesla", "Henry", "Farad", "Coulomb"],
        answer: 2,
        explanation: "Capacitance is measured in farads.",
      },
    ],
  },
  {
    subject: "Engineering Mathematics II",
    slug: "em2",
    description: "Quiz your knowledge of calculus, numerical methods, complex variables, and engineering math ideas from second semester.",
    questions: [
      {
        id: 1,
        question: "Which test checks convergence of a series by comparing it to a known convergent series?",
        options: ["Integral test", "Ratio test", "Comparison test", "Alternating series test"],
        answer: 2,
        explanation: "The comparison test compares a series to a benchmark series with known convergence.",
      },
      {
        id: 2,
        question: "What is the complex conjugate of `3 + 4i`?",
        options: ["3 - 4i", "-3 + 4i", "4 + 3i", "-3 - 4i"],
        answer: 0,
        explanation: "The complex conjugate changes the sign of the imaginary part.",
      },
      {
        id: 3,
        question: "Which method is often used to solve integrals by transforming into partial fractions?",
        options: ["Substitution", "Integration by parts", "Partial fractions", "Trigonometric substitution"],
        answer: 2,
        explanation: "Partial fraction decomposition helps integrate rational functions.",
      },
      {
        id: 4,
        question: "In numerical methods, the bisection method requires the function to be:",
        options: ["Differentiable", "Continuous", "Periodic", "Discrete"],
        answer: 1,
        explanation: "Bisection requires continuity on the interval and opposite signs at the endpoints.",
      },
      {
        id: 5,
        question: "Which function has the derivative `1/(1+x²)`?",
        options: ["arcsin(x)", "arctan(x)", "ln(x)", "e^{x}"],
        answer: 1,
        explanation: "The derivative of `arctan(x)` is `1/(1+x²)`.",
      },
      {
        id: 6,
        question: "What is the Laplace transform of `1`?",
        options: ["1/s", "s", "e^{s}", "0"],
        answer: 0,
        explanation: "The Laplace transform of 1 is `1/s`.",
      },
      {
        id: 7,
        question: "Which expression represents the magnitude of the complex number `4 + 3i`?",
        options: ["7", "5", "25", "1"],
        answer: 1,
        explanation: "Magnitude is the square root of (4² + 3²), which is 5.",
      },
      {
        id: 8,
        question: "What is the value of `∫₀¹ x² dx`?",
        options: ["1/3", "1/2", "1", "2/3"],
        answer: 0,
        explanation: "The integral of x² is x³/3; evaluated from 0 to 1 gives 1/3.",
      },
      {
        id: 9,
        question: "Which formula is used for the area of a sector of a circle with angle θ in radians?",
        options: ["½ r² θ", "r θ", "π r²", "r² θ"],
        answer: 0,
        explanation: "Area of a sector is ½ r² θ when θ is in radians.",
      },
      {
        id: 10,
        question: "Which numerical method is most appropriate for solving nonlinear equations using secant lines?",
        options: ["Newton-Raphson", "Bisection", "Secant method", "Trapezoidal rule"],
        answer: 2,
        explanation: "The secant method uses secant lines to approximate roots without derivatives.",
      },
      {
        id: 11,
        question: "What is the Laplace transform of `e^{3t}`?",
        options: ["1/(s-3)", "1/(s+3)", "s/(s^2+9)", "3/(s-1)"],
        answer: 0,
        explanation: "The Laplace transform of `e^{at}` is `1/(s-a)` for s > a.",
      },
      {
        id: 12,
        question: "The Maclaurin series for `sin(x)` begins with:",
        options: ["x + x^3/6", "x - x^3/6", "1 - x^2/2", "1 + x + x^2/2"],
        answer: 1,
        explanation: "The Maclaurin series for sin(x) starts with x - x^3/6 + ... .",
      },
      {
        id: 13,
        question: "The ratio test uses the limit of |a_{n+1}/a_n| to determine series: ",
        options: ["Sum", "Convergence", "Derivative", "Integral"],
        answer: 1,
        explanation: "The ratio test examines a series' convergence behavior.",
      },
      {
        id: 14,
        question: "What is the polar representation of the complex number 1 + i?",
        options: ["√2 cis 45°", "2 cis 90°", "1 cis 0°", "√2 cis 30°"],
        answer: 0,
        explanation: "1 + i has magnitude √2 and angle π/4 (45°).",
      },
      {
        id: 15,
        question: "Which inverse Laplace transform corresponds to `s/(s²+4)`?",
        options: ["sin(2t)", "cos(2t)", "e^{2t}", "2 cos(t)"],
        answer: 1,
        explanation: "The inverse Laplace of s/(s²+ω²) is cos(ωt).",
      },
      {
        id: 16,
        question: "Regula Falsi is another name for which root-finding method?",
        options: ["Newton-Raphson", "Bisection", "False position", "Secant method"],
        answer: 2,
        explanation: "Regula Falsi is the false position method.",
      },
      {
        id: 17,
        question: "The general solution of y' = 3y is:",
        options: ["y = 3x", "y = Ce^{3x}", "y = Cx^3", "y = 3e^x"],
        answer: 1,
        explanation: "The solution of y' = ky is Ce^{kx}.",
      },
      {
        id: 18,
        question: "Which condition is required for Newton-Raphson method to converge?",
        options: ["Function is periodic", "Derivative is nonzero near the root", "Function has no maxima", "Function is always positive"],
        answer: 1,
        explanation: "Newton-Raphson needs a nonzero derivative near the root.",
      },
      {
        id: 19,
        question: "Which function is odd?",
        options: ["x^2", "x^3", "e^x", "cos(x)"],
        answer: 1,
        explanation: "x^3 satisfies f(-x) = -f(x), so it is odd.",
      },
      {
        id: 20,
        question: "What is the real part of the complex number 2 + 5i?",
        options: ["2", "5", "7", "-2"],
        answer: 0,
        explanation: "The real part of 2 + 5i is 2.",
      },
      {
        id: 21,
        question: "Which series test is most useful for alternating series with decreasing terms?",
        options: ["Ratio test", "Integral test", "Comparison test", "Alternating series test"],
        answer: 3,
        explanation: "The alternating series test is used for decreasing alternating series.",
      },
      {
        id: 22,
        question: "Which operation converts a complex number to its polar form?",
        options: ["Addition", "Multiplication", "Finding magnitude and angle", "Differentiation"],
        answer: 2,
        explanation: "Polar form uses the number's magnitude and argument (angle).",
      },
    ],
  },
  {
    subject: "OOPs",
    slug: "oops",
    description: "Test your understanding of object-oriented programming concepts like classes, inheritance, polymorphism, and exception handling.",
    questions: [
      {
        id: 1,
        question: "Which concept of OOP allows an object to take many forms?",
        options: ["Encapsulation", "Inheritance", "Polymorphism", "Abstraction"],
        answer: 2,
        explanation: "Polymorphism allows objects to be treated as instances of their parent class.",
      },
      {
        id: 2,
        question: "Which keyword in Java is used to create a new object?",
        options: ["create", "new", "construct", "object"],
        answer: 1,
        explanation: "The `new` keyword allocates memory and constructs a new object.",
      },
      {
        id: 3,
        question: "What is the purpose of an interface?",
        options: [
          "To provide method implementations",
          "To define a contract of methods without implementation",
          "To store object data",
          "To manage memory",
        ],
        answer: 1,
        explanation: "An interface declares methods that implementing classes must define.",
      },
      {
        id: 4,
        question: "Which inheritance type allows one class to inherit from one parent only?",
        options: ["Single inheritance", "Multiple inheritance", "Multilevel inheritance", "Hierarchical inheritance"],
        answer: 0,
        explanation: "Single inheritance involves one child class inheriting from a single parent class.",
      },
      {
        id: 5,
        question: "Which keyword is used to call a parent class constructor in Java?",
        options: ["super", "this", "parent", "base"],
        answer: 0,
        explanation: "`super` invokes the parent class constructor.",
      },
      {
        id: 6,
        question: "What does encapsulation do?",
        options: [
          "Expose all data members",
          "Hide internal state and restrict access",
          "Provide multiple class forms",
          "Execute code faster",
        ],
        answer: 1,
        explanation: "Encapsulation hides internal data and exposes functionality through methods.",
      },
      {
        id: 7,
        question: "Which exception handling keyword is used to execute code regardless of whether an exception occurs?",
        options: ["try", "catch", "finally", "throw"],
        answer: 2,
        explanation: "The `finally` block runs whether an exception is thrown or not.",
      },
      {
        id: 8,
        question: "Which of these is not a pillar of OOP?",
        options: ["Abstraction", "Encapsulation", "Recursion", "Inheritance"],
        answer: 2,
        explanation: "Recursion is a programming technique, not an OOP pillar.",
      },
      {
        id: 9,
        question: "What is method overriding?",
        options: [
          "Defining a new method with a different name",
          "Replacing a parent class method in a subclass",
          "Creating multiple methods with same name and signature",
          "Calling a method from another class",
        ],
        answer: 1,
        explanation: "Overriding redefines a parent class method in a subclass.",
      },
      {
        id: 10,
        question: "Which access modifier allows a member to be visible only within its own class?",
        options: ["public", "protected", "private", "default"],
        answer: 2,
        explanation: "`private` members are only accessible inside the defining class.",
      },
      {
        id: 11,
        question: "What is method overloading?",
        options: [
          "Same method name, different parameter list",
          "Same method name, same parameters",
          "Different method name, same parameter list",
          "Different method name, different return type",
        ],
        answer: 0,
        explanation: "Overloading means defining multiple methods with the same name but different parameters.",
      },
      {
        id: 12,
        question: "Which keyword prevents a class from being subclassed?",
        options: ["abstract", "static", "final", "private"],
        answer: 2,
        explanation: "A `final` class cannot be extended.",
      },
      {
        id: 13,
        question: "What is true about an abstract class in Java?",
        options: ["It can be instantiated", "It cannot have methods", "It can contain abstract methods", "It cannot implement interfaces"],
        answer: 2,
        explanation: "Abstract classes can contain abstract methods and cannot be directly instantiated.",
      },
      {
        id: 14,
        question: "Which keyword is used to explicitly throw an exception?",
        options: ["catch", "throw", "throws", "finally"],
        answer: 1,
        explanation: "The `throw` keyword is used to throw an exception object.",
      },
      {
        id: 15,
        question: "What does try-with-resources do in Java?",
        options: ["Buffers output automatically", "Closes resources automatically", "Avoids exceptions", "Speeds compilation"],
        answer: 1,
        explanation: "try-with-resources automatically closes closable resources.",
      },
      {
        id: 16,
        question: "Which method starts a Java thread properly?",
        options: ["run()", "start()", "execute()", "launch()"],
        answer: 1,
        explanation: "`start()` begins a new thread and then calls `run()` internally.",
      },
      {
        id: 17,
        question: "What problem does the `synchronized` keyword help prevent?",
        options: ["Memory leaks", "Race conditions", "Syntax errors", "Compile-time errors"],
        answer: 1,
        explanation: "`synchronized` enforces mutual exclusion so threads cannot access shared data simultaneously.",
      },
      {
        id: 18,
        question: "Which keyword declares a generic type parameter in Java?",
        options: ["generic", "type", "T", "<T>"],
        answer: 3,
        explanation: "Generic type parameters are declared using angle brackets, for example `<T>`.",
      },
      {
        id: 19,
        question: "What does the `this` keyword refer to?",
        options: ["Class name", "Parent object", "Current object", "Static method"],
        answer: 2,
        explanation: "`this` refers to the current instance of the class.",
      },
      {
        id: 20,
        question: "Why is comparing strings with `==` usually incorrect in Java?",
        options: ["It compares content", "It compares references", "It converts strings to numbers", "It always returns false"],
        answer: 1,
        explanation: "`==` compares object references, not string contents.",
      },
      {
        id: 21,
        question: "Which Java collection class is ordered and allows duplicates?",
        options: ["HashSet", "TreeSet", "ArrayList", "HashMap"],
        answer: 2,
        explanation: "`ArrayList` preserves insertion order and allows duplicate elements.",
      },
      {
        id: 22,
        question: "Which Swing component is used as a top-level window?",
        options: ["JPanel", "JButton", "JFrame", "JLabel"],
        answer: 2,
        explanation: "`JFrame` is a top-level Swing container commonly used for main windows.",
      },
    ],
  },
  {
    subject: "Data Structures using C",
    slug: "dsc",
    description: "Practice key data structure concepts in C, including arrays, pointers, string handling, and dynamic allocation.",
    questions: [
      {
        id: 1,
        question: "Which property describes how arrays are stored in C?",
        options: ["Linked list", "Contiguous memory", "Hashed table", "Tree structure"],
        answer: 1,
        explanation: "Arrays are stored in contiguous memory locations.",
      },
      {
        id: 2,
        question: "What is the index of the first element in a C array?",
        options: ["-1", "0", "1", "Depends on size"],
        answer: 1,
        explanation: "C array indexing starts at 0.",
      },
      {
        id: 3,
        question: "In C, a two-dimensional array is stored in: ",
        options: ["Column-major order", "Row-major order", "Hash table", "Graph format"],
        answer: 1,
        explanation: "C uses row-major order for multidimensional arrays.",
      },
      {
        id: 4,
        question: "Which search examines elements one by one until it finds the target?",
        options: ["Binary search", "Linear search", "Hash search", "Depth-first search"],
        answer: 1,
        explanation: "Linear search scans elements sequentially.",
      },
      {
        id: 5,
        question: "Binary search requires the array to be: ",
        options: ["Sorted", "Linked", "Dynamic", "Circular"],
        answer: 0,
        explanation: "Binary search only works on sorted arrays.",
      },
      {
        id: 6,
        question: "Which structure follows last-in, first-out order?",
        options: ["Queue", "Stack", "Tree", "Graph"],
        answer: 1,
        explanation: "A stack is LIFO.",
      },
      {
        id: 7,
        question: "Which structure follows first-in, first-out order?",
        options: ["Stack", "Queue", "Heap", "Tree"],
        answer: 1,
        explanation: "A queue is FIFO.",
      },
      {
        id: 8,
        question: "How do you declare an integer array of size 10 in C?",
        options: ["int a;", "int a[10];", "int[10] a;", "array<int, 10> a;"],
        answer: 1,
        explanation: "C syntax for a fixed-size array is `int a[10];`.",
      },
      {
        id: 9,
        question: "What does the expression `a + 1` mean for an integer array `a`?",
        options: ["Second element address", "Array length", "Value at index 1", "Pointer to array"],
        answer: 0,
        explanation: "Pointer arithmetic moves to the next element's address.",
      },
      {
        id: 10,
        question: "How is a C string terminated?",
        options: ["\n", "\0", "EOF", "NULL"],
        answer: 1,
        explanation: "C strings end with the null character `\0`.",
      },
      {
        id: 11,
        question: "How can you compute the number of elements in a static array `arr`?",
        options: ["sizeof(arr)/sizeof(arr[0])", "length(arr)", "arr.size", "count(arr)"],
        answer: 0,
        explanation: "Using `sizeof` on the whole array divided by an element size gives length.",
      },
      {
        id: 12,
        question: "Which function allocates memory dynamically in C?",
        options: ["malloc", "alloc", "new", "reserve"],
        answer: 0,
        explanation: "`malloc` allocates raw memory in C.",
      },
      {
        id: 13,
        question: "What must you do after using `malloc` to avoid memory leaks?",
        options: ["Reuse the pointer", "Call free", "Call delete", "Set pointer to NULL only"],
        answer: 1,
        explanation: "`free` releases dynamically allocated memory.",
      },
      {
        id: 14,
        question: "Which function copies a C string from source to destination?",
        options: ["strcat", "strcmp", "strcpy", "strlen"],
        answer: 2,
        explanation: "`strcpy` copies the source string into the destination buffer.",
      },
      {
        id: 15,
        question: "Which function concatenates two C strings?",
        options: ["strcpy", "strcat", "strcmp", "strlen"],
        answer: 1,
        explanation: "`strcat` appends one string to another.",
      },
      {
        id: 16,
        question: "Which string function returns zero when two strings are equal?",
        options: ["strcmp", "strcpy", "strlen", "strcat"],
        answer: 0,
        explanation: "`strcmp` returns 0 if the strings are equal.",
      },
      {
        id: 17,
        question: "Accessing outside the bounds of an array results in: ",
        options: ["Compilation error", "Undefined behavior", "Automatic resizing", "Zero fill"],
        answer: 1,
        explanation: "Out-of-bounds access causes undefined behavior in C.",
      },
      {
        id: 18,
        question: "A circular queue uses modulo arithmetic to: ",
        options: ["Sort elements", "Wrap around the array", "Double the size", "Delete elements"],
        answer: 1,
        explanation: "Modulo arithmetic lets the queue wrap around when reaching the end.",
      },
      {
        id: 19,
        question: "What kind of data structure is a linked list node with a data field and a next pointer?",
        options: ["Tree", "Graph", "Stack", "Linked list node"],
        answer: 3,
        explanation: "A struct with data and next pointer defines a linked list node.",
      },
      {
        id: 20,
        question: "Which header provides `memcpy` and `memmove`?",
        options: ["<string.h>", "<stdlib.h>", "<stdio.h>", "<math.h>"],
        answer: 0,
        explanation: "`memcpy` and `memmove` are declared in `<string.h>`.",
      },
      {
        id: 21,
        question: "What is true about a `static` array inside a function?",
        options: ["It is allocated on the stack", "It has automatic storage duration", "It persists across function calls", "It must be freed manually"],
        answer: 2,
        explanation: "A static local array retains its value between calls.",
      },
      {
        id: 22,
        question: "Which data structure is most appropriate for LIFO access?",
        options: ["Queue", "Stack", "Binary tree", "Hash table"],
        answer: 1,
        explanation: "A stack provides last-in, first-out access.",
      },
    ],
  },
  {
    subject: "OOPs",
    slug: "oops",
    description: "Test your understanding of object-oriented programming concepts like classes, inheritance, polymorphism, and exception handling.",
    questions: [
      {
        id: 1,
        question: "Which concept of OOP allows an object to take many forms?",
        options: ["Encapsulation", "Inheritance", "Polymorphism", "Abstraction"],
        answer: 2,
        explanation: "Polymorphism allows objects to be treated as instances of their parent class.",
      },
      {
        id: 2,
        question: "Which keyword in Java is used to create a new object?",
        options: ["create", "new", "construct", "object"],
        answer: 1,
        explanation: "The `new` keyword allocates memory and constructs a new object.",
      },
      {
        id: 3,
        question: "What is the purpose of an interface?",
        options: [
          "To provide method implementations",
          "To define a contract of methods without implementation",
          "To store object data",
          "To manage memory",
        ],
        answer: 1,
        explanation: "An interface declares methods that implementing classes must define.",
      },
      {
        id: 4,
        question: "Which inheritance type allows one class to inherit from one parent only?",
        options: ["Single inheritance", "Multiple inheritance", "Multilevel inheritance", "Hierarchical inheritance"],
        answer: 0,
        explanation: "Single inheritance involves one child class inheriting from a single parent class.",
      },
      {
        id: 5,
        question: "Which keyword is used to call a parent class constructor in Java?",
        options: ["super", "this", "parent", "base"],
        answer: 0,
        explanation: "`super` invokes the parent class constructor.",
      },
      {
        id: 6,
        question: "What does encapsulation do?",
        options: [
          "Expose all data members",
          "Hide internal state and restrict access",
          "Provide multiple class forms",
          "Execute code faster",
        ],
        answer: 1,
        explanation: "Encapsulation hides internal data and exposes functionality through methods.",
      },
      {
        id: 7,
        question: "Which exception handling keyword is used to execute code regardless of whether an exception occurs?",
        options: ["try", "catch", "finally", "throw"],
        answer: 2,
        explanation: "The `finally` block runs whether an exception is thrown or not.",
      },
      {
        id: 8,
        question: "Which of these is not a pillar of OOP?",
        options: ["Abstraction", "Encapsulation", "Recursion", "Inheritance"],
        answer: 2,
        explanation: "Recursion is a programming technique, not an OOP pillar.",
      },
      {
        id: 9,
        question: "What is method overriding?",
        options: [
          "Defining a new method with a different name",
          "Replacing a parent class method in a subclass",
          "Creating multiple methods with same name and signature",
          "Calling a method from another class",
        ],
        answer: 1,
        explanation: "Overriding redefines a parent class method in a subclass.",
      },
      {
        id: 10,
        question: "Which access modifier allows a member to be visible only within its own class?",
        options: ["public", "protected", "private", "default"],
        answer: 2,
        explanation: "`private` members are only accessible inside the defining class.",
      },
      {
        id: 11,
        question: "What is method overloading?",
        options: [
          "Same method name, different parameter list",
          "Same method name, same parameters",
          "Different method name, same parameter list",
          "Different method name, different return type",
        ],
        answer: 0,
        explanation: "Overloading means defining multiple methods with the same name but different parameters.",
      },
      {
        id: 12,
        question: "Which keyword prevents a class from being subclassed?",
        options: ["abstract", "static", "final", "private"],
        answer: 2,
        explanation: "A `final` class cannot be extended.",
      },
      {
        id: 13,
        question: "What is true about an abstract class in Java?",
        options: ["It can be instantiated", "It cannot have methods", "It can contain abstract methods", "It cannot implement interfaces"],
        answer: 2,
        explanation: "Abstract classes can contain abstract methods and cannot be directly instantiated.",
      },
      {
        id: 14,
        question: "Which keyword is used to explicitly throw an exception?",
        options: ["catch", "throw", "throws", "finally"],
        answer: 1,
        explanation: "The `throw` keyword is used to throw an exception object.",
      },
      {
        id: 15,
        question: "What does try-with-resources do in Java?",
        options: ["Buffers output automatically", "Closes resources automatically", "Avoids exceptions", "Speeds compilation"],
        answer: 1,
        explanation: "try-with-resources automatically closes closable resources.",
      },
      {
        id: 16,
        question: "Which method starts a Java thread properly?",
        options: ["run()", "start()", "execute()", "launch()"],
        answer: 1,
        explanation: "`start()` begins a new thread and then calls `run()` internally.",
      },
      {
        id: 17,
        question: "What problem does the `synchronized` keyword help prevent?",
        options: ["Memory leaks", "Race conditions", "Syntax errors", "Compile-time errors"],
        answer: 1,
        explanation: "`synchronized` enforces mutual exclusion so threads cannot access shared data simultaneously.",
      },
      {
        id: 18,
        question: "Which keyword declares a generic type parameter in Java?",
        options: ["generic", "type", "T", "<T>"],
        answer: 3,
        explanation: "Generic type parameters are declared using angle brackets, for example `<T>`.",
      },
      {
        id: 19,
        question: "What does the `this` keyword refer to?",
        options: ["Class name", "Parent object", "Current object", "Static method"],
        answer: 2,
        explanation: "`this` refers to the current instance of the class.",
      },
      {
        id: 20,
        question: "Why is comparing strings with `==` usually incorrect in Java?",
        options: ["It compares content", "It compares references", "It converts strings to numbers", "It always returns false"],
        answer: 1,
        explanation: "`==` compares object references, not string contents.",
      },
      {
        id: 21,
        question: "Which Java collection class is ordered and allows duplicates?",
        options: ["HashSet", "TreeSet", "ArrayList", "HashMap"],
        answer: 2,
        explanation: "`ArrayList` preserves insertion order and allows duplicate elements.",
      },
      {
        id: 22,
        question: "Which Swing component is used as a top-level window?",
        options: ["JPanel", "JButton", "JFrame", "JLabel"],
        answer: 2,
        explanation: "`JFrame` is a top-level Swing container commonly used for main windows.",
      },
    ],
  },
  {
    subject: "Operating Systems",
    slug: "os",
    description: "Quiz yourself on operating system fundamentals including processes, scheduling, synchronization, memory, and file systems.",
    questions: [
      {
        id: 1,
        question: "Which mode has full access to hardware in an operating system?",
        options: ["User mode", "Kernel mode", "Guest mode", "Supervisor mode"],
        answer: 1,
        explanation: "Kernel mode has full access to hardware and privileged CPU instructions.",
      },
      {
        id: 2,
        question: "What is a process?",
        options: ["A running program instance", "A file on disk", "A hardware component", "A network packet"],
        answer: 0,
        explanation: "A process is an instance of a program in execution.",
      },
      {
        id: 3,
        question: "Which scheduler selects processes from the ready queue to execute next?",
        options: ["Long-term scheduler", "Medium-term scheduler", "Short-term scheduler", "I/O scheduler"],
        answer: 2,
        explanation: "The short-term scheduler chooses the next process to run on the CPU.",
      },
      {
        id: 4,
        question: "Which CPU scheduling algorithm always selects the process with the smallest next CPU burst?",
        options: ["FIFO", "Round robin", "Shortest job first", "Priority scheduling"],
        answer: 2,
        explanation: "Shortest job first selects the process with the shortest expected CPU burst.",
      },
      {
        id: 5,
        question: "What feature of round-robin scheduling defines how long each process runs before switching?",
        options: ["Priority", "Quantum", "Throughput", "Burst time"],
        answer: 1,
        explanation: "The time quantum is the fixed time slice for each process in round-robin.",
      },
      {
        id: 6,
        question: "Which synchronization primitive uses wait and signal operations?",
        options: ["Mutex", "Semaphore", "Monitor", "Barrier"],
        answer: 1,
        explanation: "Semaphores provide wait (P) and signal (V) operations for synchronization.",
      },
      {
        id: 7,
        question: "Which condition is NOT required for deadlock to occur?",
        options: ["Mutual exclusion", "Hold and wait", "No preemption", "Priority inversion"],
        answer: 3,
        explanation: "Priority inversion is not one of the four necessary deadlock conditions.",
      },
      {
        id: 8,
        question: "What is the critical section problem about?",
        options: ["Optimizing disk access", "Safe access to shared resources", "Managing user sessions", "Allocating memory"],
        answer: 1,
        explanation: "The critical section problem concerns safe access to shared data by concurrent processes.",
      },
      {
        id: 9,
        question: "Which technique divides memory into fixed-size blocks called pages?",
        options: ["Segmentation", "Paging", "Partitioning", "Swapping"],
        answer: 1,
        explanation: "Paging divides memory into fixed-size pages.",
      },
      {
        id: 10,
        question: "Which technique divides memory into variable-sized segments based on logical units?",
        options: ["Paging", "Segmentation", "Spooling", "Caching"],
        answer: 1,
        explanation: "Segmentation uses variable-sized segments aligned with program structure.",
      },
      {
        id: 11,
        question: "What is a page fault?",
        options: ["A disk failure", "A missing page in main memory", "A CPU exception", "A I/O error"],
        answer: 1,
        explanation: "A page fault occurs when a process references a page not currently in memory.",
      },
      {
        id: 12,
        question: "What is thrashing?",
        options: ["High CPU utilization", "Excessive paging activity", "Disk failure", "Network congestion"],
        answer: 1,
        explanation: "Thrashing happens when the OS spends more time paging than executing processes.",
      },
      {
        id: 13,
        question: "Which data structure stores metadata for a file in many UNIX-like file systems?",
        options: ["Heap", "Inode", "Buffer cache", "Segment table"],
        answer: 1,
        explanation: "An inode holds a file's metadata and pointers to its blocks.",
      },
      {
        id: 14,
        question: "Which scheduling algorithm services the nearest disk request first?",
        options: ["FCFS", "SSTF", "SCAN", "Priority"],
        answer: 1,
        explanation: "SSTF selects the request with the shortest seek time from the current head position.",
      },
      {
        id: 15,
        question: "Which type of fragmentation occurs when free memory is split into small noncontiguous blocks?",
        options: ["Internal fragmentation", "External fragmentation", "Cache fragmentation", "Segment fragmentation"],
        answer: 1,
        explanation: "External fragmentation occurs when there is enough total free memory but not enough contiguous block.",
      },
      {
        id: 16,
        question: "Which memory management scheme swaps entire processes between disk and main memory?",
        options: ["Paging", "Segmentation", "Swapping", "Caching"],
        answer: 2,
        explanation: "Swapping moves entire processes in and out of main memory.",
      },
      {
        id: 17,
        question: "What does virtual memory provide to a process?",
        options: ["Faster CPU", "Larger apparent address space", "Permanent storage", "Network access"],
        answer: 1,
        explanation: "Virtual memory gives each process the illusion of a larger address space.",
      },
      {
        id: 18,
        question: "Which mechanism ensures that only one thread executes a critical section at a time?",
        options: ["Segmentation", "Mutex", "Paging", "Spooling"],
        answer: 1,
        explanation: "Mutexes provide mutual exclusion for critical sections.",
      },
      {
        id: 19,
        question: "What is a context switch?",
        options: ["Switching between user and kernel mode", "Saving and restoring process state", "Loading a program from disk", "Performing I/O"],
        answer: 1,
        explanation: "A context switch saves the current process's state and restores another's.",
      },
      {
        id: 20,
        question: "Which file permission allows writing but not executing a file?",
        options: ["Read", "Write", "Execute", "Read-write"],
        answer: 1,
        explanation: "Write permission allows modifying a file's contents.",
      },
      {
        id: 21,
        question: "What is demand paging?",
        options: ["Loading all pages at once", "Loading pages only when referenced", "Swapping pages out immediately", "Preloading I/O"],
        answer: 1,
        explanation: "Demand paging loads pages only when they are actually needed.",
      },
      {
        id: 22,
        question: "Which memory allocation method can cause external fragmentation?",
        options: ["Paging", "Segmentation", "Fixed partitioning", "Dynamic partitioning"],
        answer: 3,
        explanation: "Dynamic partitioning allocates variable-size blocks and can lead to external fragmentation.",
      },
    ],
  },
  {
    subject: "Machine Learning",
    slug: "ml",
    description: "Review core machine learning topics including supervised learning, preprocessing, dimensionality reduction, and evaluation metrics.",
    questions: [
      {
        id: 1,
        question: "Which type of learning uses labeled examples?",
        options: ["Supervised", "Unsupervised", "Reinforcement", "Self-supervised"],
        answer: 0,
        explanation: "Supervised learning uses labeled training data.",
      },
      {
        id: 2,
        question: "What does a regression model predict?",
        options: ["Discrete categories", "Continuous values", "Sequence order", "Graph structure"],
        answer: 1,
        explanation: "Regression predicts continuous numeric outcomes.",
      },
      {
        id: 3,
        question: "What is overfitting?",
        options: ["Undertraining a model", "A model performing poorly on training data", "A model fitting noise in training data", "A model with too few parameters"],
        answer: 2,
        explanation: "Overfitting occurs when a model learns noise and fails to generalize.",
      },
      {
        id: 4,
        question: "Which technique helps the model generalize better by using multiple train/test splits?",
        options: ["Regularization", "Cross-validation", "Feature scaling", "Dimensionality reduction"],
        answer: 1,
        explanation: "Cross-validation evaluates models on different folds for better generalization estimates.",
      },
      {
        id: 5,
        question: "What is feature scaling used for?",
        options: ["Encoding categories", "Reducing features", "Bringing features onto similar scales", "Increasing model complexity"],
        answer: 2,
        explanation: "Feature scaling standardizes feature magnitudes so algorithms behave better.",
      },
      {
        id: 6,
        question: "What does PCA do?",
        options: ["Classify data", "Reduce dimensionality", "Normalize data", "Split data"],
        answer: 1,
        explanation: "PCA projects data into a lower-dimensional space that captures variance.",
      },
      {
        id: 7,
        question: "Which of these is a supervised dimensionality reduction method?",
        options: ["PCA", "t-SNE", "LDA", "K-means"],
        answer: 2,
        explanation: "LDA uses class labels to find directions that separate classes.",
      },
      {
        id: 8,
        question: "What is multicollinearity?",
        options: ["All features are independent", "Features are highly correlated", "Missing values in data", "Nonlinear relationships"],
        answer: 1,
        explanation: "Multicollinearity occurs when features are strongly correlated with each other.",
      },
      {
        id: 9,
        question: "Which loss function is commonly used for regression?",
        options: ["Cross-entropy", "Mean squared error", "Hinge loss", "Softmax"],
        answer: 1,
        explanation: "Mean squared error is a standard loss for regression tasks.",
      },
      {
        id: 10,
        question: "What is the purpose of one-hot encoding?",
        options: ["Scale numeric features", "Convert categorical features to binary columns", "Reduce model size", "Handle missing values"],
        answer: 1,
        explanation: "One-hot encoding converts categorical values into a binary representation.",
      },
      {
        id: 11,
        question: "What is the mean squared error (MSE)?",
        options: ["Average absolute error", "Average squared error", "Sum of errors", "Difference between max and min"],
        answer: 1,
        explanation: "MSE is the average of squared differences between actual and predicted values.",
      },
      {
        id: 12,
        question: "What does R² score measure?",
        options: ["Model accuracy", "Time complexity", "Variance explained by the model", "Number of features"],
        answer: 2,
        explanation: "R² indicates the proportion of variance in the target explained by the model.",
      },
      {
        id: 13,
        question: "What does a train/test split help prevent?",
        options: ["Underfitting", "Overfitting", "Data leakage", "Feature selection"],
        answer: 2,
        explanation: "A train/test split prevents data leakage by keeping evaluation data separate.",
      },
      {
        id: 14,
        question: "Which regularization method can produce sparse weight vectors?",
        options: ["L2", "L1", "Dropout", "Early stopping"],
        answer: 1,
        explanation: "L1 regularization tends to drive some weights to zero, producing sparsity.",
      },
      {
        id: 15,
        question: "What is the root mean squared error (RMSE)?",
        options: ["Square of MSE", "Square root of MSE", "Average absolute error", "Maximum error"],
        answer: 1,
        explanation: "RMSE is the square root of the mean squared error.",
      },
      {
        id: 16,
        question: "Which algorithm is typically used for nonlinear dimensionality reduction and visualization?",
        options: ["PCA", "LDA", "t-SNE", "Linear regression"],
        answer: 2,
        explanation: "t-SNE is a nonlinear method commonly used for visualization.",
      },
      {
        id: 17,
        question: "Which model evaluation metric is best for balanced classification accuracy?",
        options: ["MSE", "Accuracy", "R²", "Mean absolute error"],
        answer: 1,
        explanation: "Accuracy measures the fraction of correct predictions in classification.",
      },
      {
        id: 18,
        question: "What is the goal of feature selection?",
        options: ["Increase feature count", "Choose the best subset of features", "Randomize features", "Scale features"],
        answer: 1,
        explanation: "Feature selection aims to choose the most informative features and reduce noise.",
      },
      {
        id: 19,
        question: "What does gradient descent do?",
        options: ["Maximizes the loss", "Minimizes the loss by following the gradient", "Sorts features", "Normalizes data"],
        answer: 1,
        explanation: "Gradient descent updates parameters in the negative gradient direction to minimize loss.",
      },
      {
        id: 20,
        question: "Which data preprocessing step is often required before PCA?",
        options: ["One-hot encoding", "Feature scaling", "Binarization", "Label smoothing"],
        answer: 1,
        explanation: "PCA works best when features are scaled similarly.",
      },
      {
        id: 21,
        question: "Which model type is suitable when the target is a category?",
        options: ["Regression", "Classification", "Clustering", "Dimensionality reduction"],
        answer: 1,
        explanation: "Classification models are used for categorical targets.",
      },
      {
        id: 22,
        question: "What is a common symptom of multicollinearity?",
        options: ["Low training error", "High correlation among features", "Missing values", "Small dataset"],
        answer: 1,
        explanation: "Multicollinearity arises when features are highly correlated with each other.",
      },
    ],
  },
];

export function getQuizBySlug(slug: string): Quiz | undefined {
  return quizzes.find((q) => q.slug === slug);
}
